name: ManagementAgent QuickStart builds 
on:
  pull_request_target:
    types:
      - closed
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Set tag name
      run: echo "tag=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
    - name: Package ATP Monitoring
      run: |
        cd ./atp-monitoring && zip -r ../atp-monitoring.zip . && cd -
    - name: Package Helm charts
      run: |
        cd ./kubernetes-monitoring/mgmtagent_helm && zip -r ../../mgmtagent-helm.zip . && cd -
    - name: Package Management Gateway Quickstart
      run: |
        cd ./management-gateway-quickstart && zip -r ../mgmtgateway-quickstart.zip . && cd -
    - name: Package ansible playbooks
      run: |
        cd ./deployment/ansible-playbooks && zip -r ../../ansible-playbooks.zip . && cd -
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.tag }}
        release_name: Management Agent Quick Start Apps release ${{ env.tag }}
    - name: Upload ATP Monitoring Terraform package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./atp-monitoring.zip
        asset_name: atp-monitoring.zip
        asset_content_type: application/zip
    - name: Upload Helm chart package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mgmtagent-helm.zip
        asset_name: mgmtagent-helm.zip
        asset_content_type: application/zip
    - name: Upload Management Gateway Quickstart package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./mgmtgateway-quickstart.zip
        asset_name: mgmtgateway-quickstart.zip
        asset_content_type: application/zip
    - name: Upload ansible playbooks package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ansible-playbooks.zip
        asset_name: ansible-playbooks.zip
        asset_content_type: application/zip